version: "3.8"

services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-overfero}"
    image: overfero-model
    platform: linux/amd64
    container_name: overfero-model-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USERNAME:-overfero}"
        USER_ID: "${USER_ID:-1000}"
    # env_file:
    #   - .envs/.app
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME:-overfero}/.config/gcloud
    ports:
      - :8080

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

    ipc: host
    init: true